# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drone_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(626, 384)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 621, 382))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_36 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.gridLayout_19.addWidget(self.label_36, 2, 0, 1, 1)
        self.lcd_irtifa_14 = QtWidgets.QLCDNumber(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_irtifa_14.sizePolicy().hasHeightForWidth())
        self.lcd_irtifa_14.setSizePolicy(sizePolicy)
        self.lcd_irtifa_14.setProperty("intValue", 0)
        self.lcd_irtifa_14.setObjectName("lcd_irtifa_14")
        self.gridLayout_19.addWidget(self.lcd_irtifa_14, 5, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setObjectName("label_35")
        self.gridLayout_19.addWidget(self.label_35, 7, 0, 1, 1)
        self.lcd_hiz_14 = QtWidgets.QLCDNumber(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_hiz_14.sizePolicy().hasHeightForWidth())
        self.lcd_hiz_14.setSizePolicy(sizePolicy)
        self.lcd_hiz_14.setObjectName("lcd_hiz_14")
        self.gridLayout_19.addWidget(self.lcd_hiz_14, 2, 1, 1, 1)
        self.isik_carpisma_7 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isik_carpisma_7.sizePolicy().hasHeightForWidth())
        self.isik_carpisma_7.setSizePolicy(sizePolicy)
        self.isik_carpisma_7.setMinimumSize(QtCore.QSize(35, 35))
        self.isik_carpisma_7.setMaximumSize(QtCore.QSize(41, 41))
        self.isik_carpisma_7.setStyleSheet("/* Kapalı (Gri) Işık Görünümü */\n"
"QLabel {\n"
"    background-color: #555555;  /* Koyu gri renk */\n"
"    border-radius: 10px;        /* Boyut 20 ise yarısı 10\'dur. Bu kodu tam yuvarlak yapar */\n"
"    border: 1px solid #000000;  /* İnce siyah çerçeve */\n"
"}")
        self.isik_carpisma_7.setText("")
        self.isik_carpisma_7.setObjectName("isik_carpisma_7")
        self.gridLayout_19.addWidget(self.isik_carpisma_7, 0, 1, 1, 1)
        self.bar_batarya_14 = QtWidgets.QProgressBar(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_batarya_14.sizePolicy().hasHeightForWidth())
        self.bar_batarya_14.setSizePolicy(sizePolicy)
        self.bar_batarya_14.setProperty("value", 24)
        self.bar_batarya_14.setObjectName("bar_batarya_14")
        self.gridLayout_19.addWidget(self.bar_batarya_14, 7, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_8 = DronluPusula(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8.addWidget(self.widget_8)
        self.label_63 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMaximumSize(QtCore.QSize(91, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("QLabel {\n"
"    /* Yazı Tipi ve Gümüş Rengi */\n"
"    color: #E0E0E0; \n"
"    font-family: \'Consolas\', \'Segoe UI\', monospace;\n"
"    font-size: 19px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 1px;\n"
"    \n"
"    /* Arka Plan: Koyu Füme Gradyan */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 rgba(30, 30, 30, 0.9), \n"
"                                      stop:1 rgba(15, 15, 15, 0.95));\n"
"    \n"
"    /* Çerçeve Tasarımı */\n"
"    border: 1px solid #A0A0A0;\n"
"    border-top: 2px solid #FFFFFF; /* Parlak üst çizgi */\n"
"    border-radius: 4px;\n"
"    \n"
"    /* Hizalama ve Boşluk */\n"
"    padding: 3px 8px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"\n"
"/* --- HOVER ETKİSİ --- */\n"
"QLabel:hover {\n"
"    /* Yazı saf beyaza dönerek parlar */\n"
"    color: #FFFFFF; \n"
"    \n"
"    /* Çerçeve gümüşten parlak beyaza geçer */\n"
"    border-color: #FFFFFF;\n"
"    \n"
"    /* Arka plan hafifçe aydınlanır (metalik parlama hissi) */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, \n"
"                                      stop:0 rgba(50, 50, 50, 0.95), \n"
"                                      stop:1 rgba(30, 30, 30, 0.98));\n"
"    \n"
"    /* Hafif bir gölge/ışıltı efekti (Opsiyonel) */\n"
"    border-top: 3px solid #FFFFFF;\n"
"}")
        self.label_63.setObjectName("label_63")
        self.verticalLayout_8.addWidget(self.label_63)
        self.gridLayout_19.addLayout(self.verticalLayout_8, 2, 2, 7, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName("label_37")
        self.gridLayout_19.addWidget(self.label_37, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_19.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.gridLayout_19.addWidget(self.label_38, 0, 2, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_19, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_36.setText(_translate("Form", "İRTİFA"))
        self.label_35.setText(_translate("Form", "BATARYA"))
        self.label_63.setText(_translate("Form", "0°"))
        self.label_37.setText(_translate("Form", "HIZ"))
        self.label_16.setText(_translate("Form", "mod durumu"))
        self.label_38.setText(_translate("Form", "TLABEL2"))
from arayuz_pkg.pusula_kodu import DronluPusula
