# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yenitasarım.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1619, 827)
        MainWindow.setStyleSheet("/* TÜM PENCERE ARKA PLANI */\n"
"QMainWindow { \n"
"    background-color: #0F1219; \n"
"}\n"
"\n"
"/* TEXT EDIT - LOG VE MESAJ EKRANI */\n"
"QTextEdit {\n"
"    background-color: #0D1117; \n"
"    color: #00FFC2;           \n"
"    border: 1px solid #30363D;\n"
"    border-left: 3px solid #00D1FF; \n"
"    border-radius: 4px;\n"
"    font-family: \'Consolas\', \'Monaco\', \'Courier New\'; \n"
"    font-size: 11px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* KAYDIRMA ÇUBUĞU TASARIMI (Scrollbar) */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #161B22;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #30363D;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #00D1FF; \n"
"}\n"
"\n"
"/* GRUP KUTULARI (İHA Panelleri) */\n"
"QGroupBox {\n"
"    background-color: #161B22;\n"
"    border: 1px solid #30363D;\n"
"    border-radius: 8px;\n"
"    margin-top: 20px;\n"
"    color: #58A6FF;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* LCD GÖSTERGELER */\n"
"QLCDNumber {\n"
"    background-color: #000000;\n"
"    color: #00FFC2;\n"
"    border: 1px solid #30363D;\n"
"}\n"
"\n"
"/* BUTONLAR */\n"
"QPushButton {\n"
"    background-color: #1F6FEB;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #388BFD;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #388BFD;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #21262D;\n"
"    color: #8B949E;\n"
"}\n"
"\n"
"/* --- SADECE EKLENEN BATARYA KISMI --- */\n"
"QProgressBar {\n"
"    border: 1px solid #30363D;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    background-color: #0D1117;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #00F2FF; \n"
"    width: 4px;                \n"
"    margin: 1px;               \n"
"}\n"
"\n"
"/* --- SADECE EKLEDİĞİMİZ ETİKETLER --- */\n"
"QLabel {\n"
"    color: #C9D1D9;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_6.addWidget(self.textEdit_2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_6.addWidget(self.textEdit_3)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 515, 757))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem = QtWidgets.QSpacerItem(48, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(300, 35))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_10.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_10.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_10.addWidget(self.pushButton_2, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(639, 326))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMaximumSize(QtCore.QSize(639, 326))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_7.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setStyleSheet("/* Ana Kutu - Dış çerçeve burada tanımlanır */\n"
"QDoubleSpinBox {\n"
"    background-color: #000000;\n"
"    color: #00FFC2;\n"
"    border: 1.5px solid #00D1FF; /* Ana Turkuaz Çerçeve */\n"
"    border-radius: 6px;\n"
"    padding-left: 10px;\n"
"    font-family: \'Consolas\', monospace;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"/* Yukarı Butonu */\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    height: 20px;\n"
"    background-color: #12161c;\n"
"    /* ÖNEMLİ: Çerçevenin ana kutuyla çakışmaması için sağ ve üst kenarı şeffaf yapıyoruz */\n"
"    border-left: 1.5px solid #00D1FF;\n"
"    border-bottom: 0.75px solid #00D1FF;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* Aşağı Butonu */\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    width: 30px;\n"
"    height: 20px;\n"
"    background-color: #12161c;\n"
"    /* Sağ ve alt kenar ana kutunun çerçevesini kullansın diye boş bırakılır */\n"
"    border-left: 1.5px solid #00D1FF;\n"
"    border-top: 0.75px solid #00D1FF;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"/* İşaretler (Genişlikleri ve konumları sabitlendi) */\n"
"QDoubleSpinBox::up-arrow {\n"
"    image: none;\n"
"    background-color: #00FFC2;\n"
"    width: 12px; height: 2px;\n"
"    border-left: 5px solid #12161c; /* Dikey boşluk hilesi */\n"
"    border-right: 5px solid #12161c;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"    image: none;\n"
"    background-color: #FF3131;\n"
"    width: 12px; height: 2px;\n"
"}\n"
"\n"
"/* HOVER DURUMLARI - Çerçevenin bozulmaması için sadece iç rengi değiştirir */\n"
"QDoubleSpinBox::up-button:hover { background-color: #00D1FF; }\n"
"QDoubleSpinBox::down-button:hover { background-color: #FF3131; }")
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setReadOnly(False)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_7.addWidget(self.doubleSpinBox, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #000000;\n"
"    color: white; /* Yazılar tamamen beyaz */\n"
"    border: 1.5px solid #00D1FF; /* Senin ikonik turkuaz çerçeven */\n"
"    border-radius: 6px;\n"
"    padding-left: 12px;\n"
"    padding-right: 12px;\n"
"    font-family: \'Consolas\', monospace; /* Teknik/Kod fontu */\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"/* Kutuya tıklandığında (Odaklandığında) */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00FFC2; /* Daha parlak bir turkuaz/yeşil vurgu */\n"
"    background-color: #050505;\n"
"}\n"
"\n"
"/* Mouse ile üzerine gelindiğinde hafif parlasın */\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid #ffffff; /* Çerçeve beyaza yaklaşsın */\n"
"}\n"
"\n"
"/* Yazı yazılamaz (Pasif) durumdayken */\n"
"QLineEdit:disabled {\n"
"    background-color: #12161c;\n"
"    color: #555555;\n"
"    border: 1.5px solid #333333;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_8.addWidget(self.lineEdit, 4, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #000000;\n"
"    color: white; /* Yazılar tamamen beyaz */\n"
"    border: 1.5px solid #00D1FF; /* Senin ikonik turkuaz çerçeven */\n"
"    border-radius: 6px;\n"
"    padding-left: 12px;\n"
"    padding-right: 12px;\n"
"    font-family: \'Consolas\', monospace; /* Teknik/Kod fontu */\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"/* Kutuya tıklandığında (Odaklandığında) */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00FFC2; /* Daha parlak bir turkuaz/yeşil vurgu */\n"
"    background-color: #050505;\n"
"}\n"
"\n"
"/* Mouse ile üzerine gelindiğinde hafif parlasın */\n"
"QLineEdit:hover {\n"
"    border: 1.5px solid #ffffff; /* Çerçeve beyaza yaklaşsın */\n"
"}\n"
"\n"
"/* Yazı yazılamaz (Pasif) durumdayken */\n"
"QLineEdit:disabled {\n"
"    background-color: #12161c;\n"
"    color: #555555;\n"
"    border: 1.5px solid #333333;\n"
"}")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_8.addWidget(self.lineEdit_2, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_8.addWidget(self.pushButton_5, 5, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 1, 1, 2, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_8.addWidget(self.pushButton_6, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 2, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 1, 1, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1619, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "KALKIŞ"))
        self.pushButton_3.setText(_translate("MainWindow", "BEKLEME"))
        self.pushButton_2.setText(_translate("MainWindow", "ACİL İNİŞ"))
        self.groupBox_5.setTitle(_translate("MainWindow", "HARİTA"))
        self.label.setText(_translate("MainWindow", "KALKIŞ YÜKSEKLİĞİ"))
        self.pushButton_4.setText(_translate("MainWindow", "GİRİŞ"))
        self.pushButton_5.setText(_translate("MainWindow", "GİRİŞ"))
        self.label_4.setText(_translate("MainWindow", "   BOYLAM"))
        self.pushButton_6.setText(_translate("MainWindow", "GİRİŞ"))
        self.label_3.setText(_translate("MainWindow", "   ENLEM"))
